CREATE TABLE if not exists article
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255),
    content   VARCHAR(255),
    author_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_article PRIMARY KEY (id)
);

CREATE TABLE if not exists my_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255),
    CONSTRAINT pk_myuser PRIMARY KEY (id)
);

ALTER TABLE article
    ADD CONSTRAINT if not exists FK_ARTICLE_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES my_user (id);